import { createHash, randomBytes } from "crypto";
import bcrypt from "bcryptjs";
import prisma from "../../config/prisma";
import { config } from "../../config";
import { logger } from "../../utils/logger";
import { sendEmail } from "../../utils/email";
import { BadRequestError } from "../../utils/AppError";

/**
 * Password reset by emailed link.
 *
 * This replaces an OTP flow that emailed a six-character code. A link is what
 * was asked for and is also the safer of the two here: the old code was
 * generated by the same helper used for temporary passwords, had no expiry
 * enforced on read, and was verified by an endpoint that took a userId
 * straight from the request body.
 *
 * Four properties this flow has to hold:
 *
 * 1. IT DOES NOT SAY WHETHER THE ACCOUNT EXISTS. The old endpoint answered
 *    "User not found" for an unknown address, which is an account enumeration
 *    oracle — the same one that was closed on the sign-in path. Every request
 *    now gets the same answer whether or not there is an account.
 *
 * 2. THE TOKEN IS NEVER STORED. Only its SHA-256 hash is, so a database
 *    backup cannot be turned into working reset links. The token exists in the
 *    email and nowhere else.
 *
 * 3. SINGLE USE, TIME LIMITED. A used link is refused explicitly rather than
 *    silently, and any older outstanding links for that account are invalidated
 *    when a new one is issued — otherwise requesting a second link would leave
 *    the first one live.
 *
 * 4. RESETTING ENDS EVERY SESSION. Someone resetting a password may be doing it
 *    because an attacker holds their old one; leaving the attacker's refresh
 *    tokens alive would defeat the point.
 */

/** Short enough to limit exposure of a link sitting in an inbox. */
const TOKEN_TTL_MINUTES = 60;

/** 32 random bytes, hex encoded. Not derived from anything about the user. */
function generateToken(): string {
  return randomBytes(32).toString("hex");
}

function hashToken(token: string): string {
  return createHash("sha256").update(token).digest("hex");
}

function resetUrl(token: string): string {
  // The link points at the FRONTEND, which collects the new password and posts
  // it back. Pointing it at the API would mean the API rendering a form.
  const base = (config.appUrl ?? "http://localhost:3000").replace(/\/+$/, "");
  return `${base}/reset-password?token=${token}`;
}

export interface RequestResetResult {
  /** Always the same, whatever happened. See property 1 above. */
  message: string;
  /**
   * Populated ONLY outside production and only when mail is unconfigured, so a
   * developer can follow the flow without an SMTP account. Never returned when
   * NODE_ENV is production, whatever the mail configuration is.
   */
  devResetUrl?: string;
}

const UNIFORM_RESPONSE =
  "If that email address has an account, a password reset link is on its way.";

export async function requestPasswordReset(
  emailId: string,
  requestIp?: string,
): Promise<RequestResetResult> {
  const user = await prisma.user.findFirst({
    where: { emailId, isDelete: "false_" as never },
    select: { id: true, emailId: true, firstName: true, status: true },
  });

  // No account, or a disabled one: stop here, but answer exactly as if a link
  // had been sent. The work skipped is not observable in the response.
  if (!user || String(user.status) === "false_") {
    logger.info(
      `Password reset requested for an address with no active account; responding uniformly`,
    );
    return { message: UNIFORM_RESPONSE };
  }

  // Any link already outstanding for this account stops working now. Issuing a
  // second link must not leave the first one usable.
  await prisma.passwordResetToken.updateMany({
    where: { userId: user.id, usedAt: null },
    data: { usedAt: new Date() },
  });

  const token = generateToken();
  const expiresAt = new Date(Date.now() + TOKEN_TTL_MINUTES * 60 * 1000);

  await prisma.passwordResetToken.create({
    data: {
      userId: user.id,
      tokenHash: hashToken(token),
      expiresAt,
      requestIp: requestIp ?? null,
    },
  });

  const url = resetUrl(token);
  const sent = await sendEmail({
    to: user.emailId,
    subject: "Reset your password",
    html: [
      `<p>Hello ${user.firstName || "there"},</p>`,
      `<p>Use the link below to choose a new password. It works once and expires in ${TOKEN_TTL_MINUTES} minutes.</p>`,
      `<p><a href="${url}">Reset your password</a></p>`,
      `<p>If you did not ask for this, you can ignore this email — your password has not changed.</p>`,
    ].join(""),
    text: `Reset your password (valid for ${TOKEN_TTL_MINUTES} minutes, one use): ${url}`,
  });

  if (!sent) {
    // The token is still valid; only delivery failed. Say so in the log rather
    // than in the response, which must stay uniform.
    logger.warn(
      "Password reset link could not be emailed — outbound mail is not configured.",
    );
    if (config.nodeEnv !== "production") {
      return { message: UNIFORM_RESPONSE, devResetUrl: url };
    }
  }

  return { message: UNIFORM_RESPONSE };
}

export interface ResetResult {
  message: string;
}

export async function resetPasswordWithToken(
  token: string,
  newPassword: string,
): Promise<ResetResult> {
  const record = await prisma.passwordResetToken.findUnique({
    where: { tokenHash: hashToken(token) },
    include: { user: { select: { id: true, isDelete: true, status: true } } },
  });

  // Unknown token. Deliberately the same message as an expired one: telling the
  // difference would confirm that a guessed token had once been real.
  if (!record) {
    throw new BadRequestError("This reset link is invalid or has expired");
  }

  if (record.usedAt) {
    // Distinguished on purpose — this is the common honest case of clicking the
    // link twice, and "already used" tells the person what to do next.
    throw new BadRequestError(
      "This reset link has already been used. Request a new one.",
    );
  }

  if (record.expiresAt.getTime() <= Date.now()) {
    throw new BadRequestError("This reset link is invalid or has expired");
  }

  if (record.user.isDelete === ("true_" as never) || String(record.user.status) === "false_") {
    throw new BadRequestError("This account is no longer active");
  }

  const hashed = await bcrypt.hash(newPassword, 10);

  // One transaction: set the password, burn the token, and end every session.
  // If any part fails, none of it applies — a password changed without the
  // token being burned would leave a reusable link.
  await prisma.$transaction([
    prisma.user.update({
      where: { id: record.userId },
      data: { password: hashed },
    }),
    prisma.passwordResetToken.update({
      where: { id: record.id },
      data: { usedAt: new Date() },
    }),
    // See property 4: the person resetting may be locking an attacker out.
    prisma.refreshToken.updateMany({
      where: { userId: record.userId, revokedAt: null },
      data: { revokedAt: new Date() },
    }),
  ]);

  logger.info(`Password reset completed for user ${record.userId}; sessions revoked`);

  return { message: "Your password has been reset. You can now sign in." };
}
